export const menuItems = [
  {
    id: 1,
    name: 'Greek Salad',
    description: 'The famous greek salad of crispy lettuce, peppers, olives and our Chicago...',
    price: 12.99,
    category: 'starters',
    image: '🥗',
  },
  {
    id: 2,
    name: 'Bruschetta',
    description: 'Our Bruschetta is made from grilled bread that has been smeared with garli...',
    price: 7.99,
    category: 'starters',
    image: '🍞',
  },
  {
    id: 3,
    name: 'Grilled Fish',
    description: 'Barbequed catch of the day, with red onion, crisp capers, chive creme fraiche,',
    price: 20.00,
    category: 'mains',
    image: '🐟',
  },
  {
    id: 4,
    name: 'Pasta',
    description: 'Penne with fried aubergines, tomato sauce, fresh chilli, garlic, basil & salted...',
    price: 18.99,
    category: 'mains',
    image: '🍝',
  },
  {
    id: 5,
    name: 'Lemon Dessert',
    description: 'Light and fluffy traditional homemade Italian Lemon and ricotta cake',
    price: 6.99,
    category: 'desserts',
    image: '🍰',
  },
  {
    id: 6,
    name: 'Iced Tea',
    description: 'Refreshing homemade iced tea with lemon',
    price: 3.99,
    category: 'drinks',
    image: '🍹',
  },
  {
    id: 7,
    name: 'Hummus',
    description: 'Creamy chickpea dip with olive oil and pita bread',
    price: 8.99,
    category: 'starters',
    image: '🥙',
  },
  {
    id: 8,
    name: 'Lamb Kebab',
    description: 'Tender grilled lamb skewers with herbs and spices',
    price: 22.99,
    category: 'mains',
    image: '🍖',
  },
  {
    id: 9,
    name: 'Baklava',
    description: 'Sweet pastry with honey and nuts',
    price: 5.99,
    category: 'desserts',
    image: '🥮',
  },
  {
    id: 10,
    name: 'Fresh Lemonade',
    description: 'Freshly squeezed lemon juice with mint',
    price: 4.99,
    category: 'drinks',
    image: '🍋',
  },
];